# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_allowedmaildomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEMailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=75)),
            ],
        ),
    ]
