# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 08:59
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.sites.models import Site

from ANDI.local_settings import DOMAIN


def insert_sites(apps, schema_editor):
    Site.objects.all().delete()

    # Register SITE_ID = 1
    Site.objects.create(pk=1, domain=DOMAIN, name=DOMAIN)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_sites)
    ]
